### ISSUE TITLE
html - index file

### ISSUE THREAD

**Issue by riwa73** [nicoeinsidler/pigor#6]
it would be nice if in the root testfile directory a html index file would be created,
that lists and links to all html output files.

**Comment by nicoeinsidler** [comment]
Great idea! Just to be sure: You want PIGOR to create only one index file, or do you want to have an index for each directory/subdirectory?

**Comment by riwa73** [comment]
Good question - I would say one index for all files - with the newest entries on top.

**Comment by nicoeinsidler** [comment]
Okay, so I just created a new branch for this feature (improvement/index-file). (I should have called it feature/index-file)

Right now I implemented it as follows:

- only entries that have a corresponding Markdown or HTML document will be listed
- the list is ordered alphabetically
- all files and folders will be found (even if recursive mode is off), because it can happen that the user wants to disable recursive mode after he already ran PIGOR in recursive mode. So it will find those files as well.

Is that this the desired behavior?

**Comment by riwa73** [comment]
almost ;-)
what I have in mind is, that if you make a measurement and have the indexfile open in your browser.
I want to run pigor - update my browser -  and have the new measurments on top to select .
so maybe not sorted alphabetically but chronically

**Comment by nicoeinsidler** [comment]
This is a great idea, but PIGOR is not meant to be run only on one file at a time. It analyses every file. So this ordering does not make sense.

However I want to add an interactive mode where the user will be able to select certain files with auto completion, but this is going to take some time.

In the mean time, I can offer to sort them by measurement date (in the file name), because we can assume that the user is interested in the most recent measurements. This is done now automatically by the file system, but not across folders, which I could implement. Should I?

**Comment by riwa73** [comment]
That makes sense and was what I intended
;-)

**Comment by nicoeinsidler** [comment]
Implemented now with ae1e24708ddaa673cd0eb2a0df551692120f6491
